### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by robotastic** [kchmck/p25rx#1]
This and the P25 Rust decoders look really cool. I put together a GnuRadio C++ based P25 Trunking recorder, but I am betting this runs a little leaner. How tough is it to get up an running?

**Comment by kchmck** [comment]
Hey, thanks for checking it out. I'll try to write up a quick readme today, but it's hopefully not too hard to get running on linux (should just need nightly rust, cargo, and librtlsdr). As far as the performance goes, it's able to hop around control/traffic channels and decode packets and voice in real time on the raspi 2, typically using about 25% of the 4 cores. The p25 and dsp crates use zero allocations and imbe uses zero except when spawning threads.

Right now I'm working in the [dev branch](https://github.com/kchmck/p25rx/tree/dev) to polish off HTTP event streaming, which sends out trunking and other updates to subscribed clients. There's a very WIP interface for it over at [p25gui](https://github.com/kchmck/p25gui).

If you're interested in the trunking area, there may be some missing [packet definitions](http://kchmck.github.io/doc/p25/trunking/index.html) since I did the original implementation with a pretty old/cheap standard during my thesis, but things like channel grants and network status updates are in there. Otherwise, there's also a good bit of work remaining to make the receiver trunking policy smarter, especially in something like a talkgroup selection algorithm.
