### ISSUE TITLE
Output printed to screen, no FIFO data

### ISSUE THREAD

**Issue by yuvadm** [kchmck/p25rx#2]
Trying to test this neat package on a known control channel, getting lots of output such as this:

```
pos:0.33833218 mid:0.10275479 neg:-0.1328226
pos:0.33840978 mid:0.10276653 neg:-0.13287671
pos:0.3382994 mid:0.10275908 neg:-0.13278124
```

But nothing on the FIFO. What do these values mean? Any further way to debug how well the channel is being received?

**Comment by kchmck** [comment]
Sorry for the lack of docs around this project, it's still WIP unfortunately. Probably the easiest way to see what's going on is to check out the raw SSE stream with
```
curl http://localhost:8025/subscribe
```
and you should see something like
```
data:{"event":"networkStatus","payload":{"area":0,"wacn":781824,"system":840}}

data:{"event":"rfssStatus","payload":{"area":0,"system":840,"rfss":2,"site":1}}

data:{"event":"altControl","payload":{"rfss":2,"site":1,"freq":774281250}}

data:{"event":"altControl","payload":{"rfss":2,"site":1,"freq":774531250}}

data:{"event":"adjacentSite","payload":{"area":0,"rfss":2,"system":840,"site":27,"freq":773081250}}

data:{"event":"sigPower","payload":21.508484}

data:{"event":"sigPower","payload":21.38679}

data:{"event":"networkStatus","payload":{"area":0,"wacn":781824,"system":840}}

data:{"event":"rfssStatus","payload":{"area":0,"system":840,"rfss":2,"site":1}}

data:{"event":"altControl","payload":{"rfss":2,"site":1,"freq":774531250}}

data:{"event":"altControl","payload":{"rfss":2,"site":1,"freq":773831250}}

data:{"event":"adjacentSite","payload":{"area":0,"rfss":2,"system":840,"site":17,"freq":774831250}}

data:{"event":"sigPower","payload":21.353647}

data:{"event":"curFreq","payload":770006250}

data:{"event":"talkGroup","payload":{"Other":14492}}
```
if trunking packets are being received.

Edit: The `curFreq` and `talkGroup` events indicate that it's selected a talkgroup and tuned to its traffic channel frequency, which should lead to some audio being output.

There's also a very [rough gui](https://github.com/kchmck/p25gui) to display that info in a streaming webpage.

I accidentally committed those log messages, but they're printing out the thresholds for the symbol decisions after it synchronizes. It looks like it might be syncing decently because the thresholds aren't changing very much!

**Comment by yuvadm** [comment]
@kchmck Thanks for the suggestion, indeed I'm getting lots of packets, similar to those you pasted, but none of types `talkGroup`. Any idea what this channel is? Is it possible that `talkGroup` packets are encrypted?

**Comment by kchmck** [comment]
I believe only control channels carry trunking packets, so it's likely you're on a valid control channel if you're seeing events like `rfssStatus`, etc. I guess it's always possible that there's just no voice traffic on that particular site, although that becomes less likely the longer the receiver sits on it. Encryption is also very possible. Probably just as likely to be a bug too.

I've pulled in the log crate and sprinkled in some log messages that might be helpful in 7660000. If you want to pull that and rebuild, you can use `-v` or `-vv` to see if there are any more clues.
